Yubico/yubico-pam

README

Hi,
Just received my yubikey neo-n and tried to install on a vagrant install of ubuntu 14.04. But was really confused by the different notions of id's in the documentation and also the fact that some test id (16 and 19) where used in the documentation. So I clarified the docs on this, hopefully helping others get up to speed quicker in the future.
Thanks for an excellent product!

Clarified the notion of id when using the pam_yubico module

---

pam_yubico.c

Compiling on OS X 10.10 with clang-600.0.57 raises a couple of warnings. Here are patches to fix them.

Fix warnings on OS X with clang

---

tests/util_test.c
util.c

Adds support for comments (indicated by lines starting with '#') in authfiles.

Support comments in authfile

---

doc/Authentication_Using_Challenge-Response.adoc

Changed all occurences of /etc/yubico to /var/yubico to preserve consistency and follow [Unix Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard).
The example in the third paragraph was misleading but it fits the standard better. So I suggest to adjust the command line instructions accordingly.

Changed /etc/yubico to /var/yubico

---

doc/Authentication_Using_Challenge-Response.adoc

The previous instructions create a global word-writeable path for challenge files. This is a security issue because all users and unprivileged processes can create challenge files for arbitrary users. This enables an attacker to bypass the second factor for authentication.

Security: Storage of challenges in path with restricted permissions

---

pam_yubico.c
tests/util_test.c
util.c
util.h

Hi, I wanted to use nullok flag with challenge-response mode so I added the support. I hope it will be helpful.
It solves issue "Cannot login with nullok using challenge-response? #119"

add nullok support to challenge-response mode

---

README

Added an example of the full ldap_bind_user DN syntax, and use a dedicated attribute for YubiKey public ID storage instead of "pager", since there are working schema extensions for this.
Rename domain used to reflect common Active Directory practice and convention for examples.

Clarify documentation;  link to sample AD schema extension

---

pam_yubico.8.txt
pam_yubico.c

This adds missing documentation of the nullok parameter to the man page and makes sure the parameter is printed out in debug mode, which has been forgotten previously.

Improvements for nullok parameter

---

.travis.yml

Since the install script currently requires sudo, we should state so
explicetely in the .travis.yml file to make sure we get a sudo-enabled
environment and not a container-based one, as there is no sudo available
in the latter one. The default was changed in August 2017, so when
forking this repository, the Travis CI won't work out-of-the box without
this modification. This is described in some details [here](https://docs.travis-ci.com/user/reference/overview/).

Require sudo in .travis.yml

---

tests/util_test.c

The latter function is considered insecure and deprecated on some platforms.
This will create the directory with 0700 implicitely, where it was 0755
beforehand. Since this is a more secure default and the test suite runs fine,
we don't bother to chmod the directory.

util_test: Use mkdtemp() instead of tempnam()

---

pam_yubico.c
util.c

This fixes several specifiers to better represent the data type, which fixes
multiple compiler warnings.

Fix several format string specifiers

---

pam_yubico.c
util.c
ykpamcfg.c

This series makes use of the O_CLOEXEC flag whenever opening file descriptor, which makes sure that those file descriptors won't be leaked into child processes, even if a final `fclose()` is forgotten (as was the case with #136).

Make use of the O_CLOEXEC flag when dealing with file descriptors

---

pam_yubico.8.txt
pam_yubico.c
ykpamcfg.1.txt
ykpamcfg.c

Certain phrases (Challenge-response) were not spelled consistently
throughout the project. This commit adjusts for that and fixes a
couple of typos along the way and uses the base form of verbs in
case of error messages.

Fix a couple of typos and spell phrases more consistently

---

README

This adds a short section about the chalresp_path option, which was missing
previously from the overview of available options in the README file.

README: Add a section about chalresp_path

---

README
pam_yubico.8.txt

This adds documentation about the cainfo parameter to both the README as
well as the man page.

Add documentation for cainfo option

---

README

This adds a Travis build status badge to the README file, so the current
status can be seen on the GitHub page instantly.

README: Add Travis build status

---

ykpamcfg.c

This series contains a couple of commits dealing with potential issues with buffer handling. Nothing too severe, but nevertheless best practices should be used.

Several hardenings and buffer handling improvements for ykpamcfg

---

util.c

This evaluates the return code from generate_random() within
write_chalresp_state() and returns immediately in case of an error.
This fixes #161.

util.c: Check whether generate_random() was invoked successfully

---

pam_yubico.c
util.c
ykpamcfg.c

This series makes sure that the return code of snprintf() is always evaluated correctly to make sure it does not run into errors silently.

General snprintf() hardenings

---

pam_yubico.c
util.c
ykpamcfg.c

This makes sure that file descriptors will be closed, even if the
fdopen() call failes, which was overlooked in some cases beforehand.
Should be not an issue in the real world, but let's be as clean as
possible.

Close file descriptors in case fdopen() fails

---

tests/pam_test.c

Compiler cannot find the declaration for `pm_sm_authenticate` and prints
the following warning:
```
pam_test.c:184:10: warning: implicit declaration of function ‘pam_sm_authenticate’;
did you mean ‘pam_authenticate’? [-Wimplicit-function-declaration]
```

Fix compiler warning in pam_test.c

---

pam_yubico.c

mkostemp() requires the _GNU_SOURCE feature test macro.
See man 3 mkostemp.

Fix implicit declaration warning of mkostemp

---

README
pam_yubico.8.txt
pam_yubico.c

As raised in #174, ldap_bind_as_user cannot be used if this module is set to get YubiKey+OTP because the initial ldap lookup fails (since the password is not set yet).  `always_prompt` will stil the initial lookup, meaning that the user will be given the chance to enter their password.

Add always_prompt configuration option to skip initial check for YubiKey

---

pam_yubico.c

Ensure that the debug log always outputs a valid OTP and not an accidental password

---

pam_yubico.c

The previous code was using a trick of saving the actual retval value
as the "pointer". The problem with that was when pam_get_data copied
it out it treated it as a void* which is 8 byte on 64 bit operating
system which meant it copied 8 byte to a 4 byte location and overwrote
the stack with 4 bytes.
The fix is using a heap pointer instead, influenced by the official
code in https://github.com/linux-pam/linux-pam/blob/master/modules/pam_unix/pam_unix_auth.c
See this gdb session for "proof" of corruption with the previous code:
``` 
Thread 1 "login" hit Breakpoint 3, 0x00007ffff5b25645 in pam_sm_acct_mgmt (pamh=0x5555557632e0, flags=0, argc=3, argv=0x5555557a02e0)
at pam_yubico.c:1330
1330      int rc = pam_get_data(pamh, "yubico_setcred_return", (const void**)&retval);
1: x/10i $rip
=> …
```

Fix pam_get_data stack overwrite by saving a heap pointer instead

---

Makefile.am
doc/YubiKey_and_SELinux.adoc

Doc: Use debug_file with sshd and SELinux

---

pam_yubico.c

When retrieving the token from LDAP the `strncmp` should not be against the length of either the input or the value from LDAP, but from the configured token length expected by the module.

Compare Token from LDAP and Input Against Configured Length

---

.github/workflows/scan.yml

This only runs on push for now so PRs are not covered. PRs are special in that if it comes from a fork it does not have access to the docker registry secrets in the repo but I have found no way of testing for the presence from within a github flow.
As of today the scanners show no warnings.

Adding a static code analysis github workflow

---

ykpamcfg.1.txt

Exectuable is named `ykpamcfg` but man pages referred to it as `ykmapcfg`. Fixed that.

Fix typo in man pages

---

.github/workflows/codeql-analysis.yml

https://github.blog/2020-09-30-code-scanning-is-now-available/

actions: CodeQL scanner

---

tests/util_test.c
util.c
util.h

This update implements RFC4515 for the username, which replaces `% u` in the LDAP search filter.
A detailed description can be found in issue #223.

RFC4515 support added to %u in ldap search filter (#223)
